import turtle as t
t.shape("turtle")
t.fd(100)   # 앞 == t.forward(100)
t.back(50)  # 뒤 == t.backward(50)
t.lt(45)    # 왼쪽 == t.left(45)
t.rt(45)    # 오른쪽 == t.right(45)
t.circle(50)
t.pendown()
t.fd(100)
t.penup()
t.lt(90)
t.fd(100)
t.down() # pendown()
t.up() # pendup()
t.down()
t.lt(90)
t.fd(50)

t.speed(10)
t.fd(100)
t.lt(90)
t.speed(1)
t.fd(100)
t.lt(90)
t.color("red")
t.pensize(5)
t.fd(50)
t.bgcolor("grey") # 배경색
t.fillcolor("green") # 거북이 색깔
t.circle(50)
t.fd(100)
t.begin_fill()
t.fillcolor("green")
t.circle(50)
t.end_fill() # begin ~ end 사이 색칠
t.st()
t.showturtle()
t.clear()
t.reset()
t.hideturtle()
t.showturtle()
t.ht()
t.st()

